# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: S Å G T A N D
email: info@sågtand.se
description: >
  S Å G T A N D är ett Göteborgsbaserat musikaliskt och tekniskt samarbete 
  för att undersöka den elektroniska musikens möjligheter.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sagtand.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  sagtand

# Build settings
markdown: kramdown

include: [".htaccess"]

# Set default values so you don't have to repeat yourself
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerpt_separator: <!--more-->
      permalink: /:title/
      layout: "post"
      author: "Jonas"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Jonas"